### ISSUE TITLE
Syntax error CLI-recovery-tool.js on Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by mseeder** [LedgerHQ/ripple-recovery-tool#2]
Nodejs & git are up to date from ubuntu 16.04 packages

Warnings on npm install:

WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
m WARN ripple-recovery-tool@0.0.1 No repository field.
nnpm WARN ripple-recovery-tool@0.0.1 No license field.

On start with node CLI-recovery-tool.js:

CLI-recovery-tool.js:1
(function (exports, require, module, __filename, __dirname) { const {**RippleAPI**} = require('./ripple-lib/dist/npm/index.js');
                                                                    **^**
**SyntaxError**: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by amougel** [comment]
The Syntax error on the `const {RippleAPI} = require('./ripple-lib/dist/npm/index.js');` suggests that your version of node is too old and does not support ES6 syntax. Try to reinstall nodejs and make sure your `node` command points to the updated version

**Comment by mseeder** [comment]
OK, it works with updated nodejs. It is possible to create a Ripple secret from the public & private key listened by the bip tool? So that we can recover by import the ripple wallet into Gatehub or the original Desktop based Ripple Wallet?

**Comment by amougel** [comment]
No, it is impossible.
