### ISSUE TITLE
ValidationError: instance.payment.source is not exactly one from <sourceExactAdjustment>...

### ISSUE THREAD

**Issue by estevaocm** [LedgerHQ/ripple-recovery-tool#4]
Hello,

When trying to recover my assets, I get the following error. Please help.

```
readline.js:1021
            throw err;
            ^

ValidationError: instance.payment.source is not exactly one from <sourceExactAdjustment>,<maxAdjustment>,instance.payment.destination is not exactly one from <destinationExactAdjustment>,<minAdjustment>
    at Object.schemaValidate (E:\downloads\ripple-recovery-tool\ripple-lib\dist\npm\common\schema-validator.js:145:15)
    at apply (E:\downloads\ripple-recovery-tool\ripple-lib\node_modules\lodash\lodash.js:496:27)
    at Object.wrapper [as preparePayment] (E:\downloads\ripple-recovery-tool\ripple-lib\node_modules\lodash\lodash.js:5356:16)
    at RippleAPI.preparePayment (E:\downloads\ripple-recovery-tool\ripple-lib\dist\npm\transaction\payment.js:106:14)
    at send (E:\downloads\ripple-recovery-tool\CLI-recovery-tool.js:109:16)
    at E:\downloads\ripple-recovery-tool\CLI-recovery-tool.js:68:21
    at E:\downloads\ripple-recovery-tool\node_modules\prompt\lib\prompt.js:316:32
    at E:\downloads\ripple-recovery-tool\node_modules\async\lib\async.js:142:25
    at assembler (E:\downloads\ripple-recovery-tool\node_modules\prompt\lib\prompt.js:313:9)
    at E:\downloads\ripple-recovery-tool\node_modules\prompt\lib\prompt.js:322:32
```

**Comment by estevaocm** [comment]
Tryed a smaller amount and got:

```
(node:13940) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ValidationError: instance.secret is not of a type(s) string,instance.secret does not conform to the "secret" format
(node:13940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm actually testing with a BIP44 private key from a BIP39 mnemonic.

**Comment by estevaocm** [comment]
I managed to solve my immediate problem by using https://github.com/ripplerm/ripple-wallet/
If this issue is not helpful, feel free to close it.

**Comment by amougel** [comment]
Were you using your private key or your secret? This tool is only designed for usage with a private key.

**Comment by estevaocm** [comment]
Hello @amougel, thank you for your attention.

I actually never had a secret key. I generated a master private key with BIP39 (https://github.com/iancoleman/bip39) and then the address and respective private key with BIP44 (with the same tool). Then I tried transferring the assets to an exchange and failed.

I was able to transfer with the Ripple wallet at https://github.com/ripplerm/ripple-wallet/

I realize your goal is to support Ledger users, which I am not at the moment. And I have solved my problem. But I thought you should know of this limitation in the current implementation.

Best regards.

**Comment by amougel** [comment]
Thanks for the notification, the tool is indeed broken due to discontinued npm librairies... We ll work on making it work anew.
